### ISSUE TITLE
Todo (REST Api)

### ISSUE THREAD

**Issue by kirchner** [kirchner/parse#1]
- [ ] Objects
    - [ ] Data Types
    - [x] Creating
    - [x] Retrieving
    - [x] Updating
    - [x] Deleting
    - [ ] Batch Operations
- [ ] Queries
    - [x] Basic Queries
    - [ ] Constraints
        - [ ] Array Values
        - [ ] String Values
    - [ ] Relational Queries
    - [x] Counting Objects
    - [x] Compound Queries
    - [ ] Aggrate Queries
- [ ] Users
    - [x] Signing Up
    - [x] Logging In
    - [x] Verifying Emails
    - [x] Requesting A Password Reset
    - [ ] Retrieving Users
    - [x] Validating Session Tokens / Retrieving Current User
    - [x] Updating Users
    - [x] Querying
    - [x] Deleting Users
    - [ ] Linking Users
    - [ ] User Security
- [x] Sessions
    - [x] Session Properties
    - [x] Handling Invalid Session Token Error
    - [x] Creating Sessions
    - [x] Retrieving Sessions
    - [x] Updating Sessions
    - [x] Querying Sessions
    - [x] Deleting Sessions
    - [x] Pairing Session with Installation
    - [x] Session Security
- [x] Roles
    - [x] Creating Roles
    - [x] Retrieving Roles
    - [x] Updating Roles
    - [x] Deleting Roles
    - [x] Security with Role
    - [x] Role Hierarchy
- [x] Files
    - [x] Uploading Files
    - [x] Associating with Objects
    - [x] Deleting Files
- [x] Config
- [x] Analytics
    - [x] App-Open Analytics
    - [x] Custom Analytics
- [x] Cloud Code
    - [x] Calling Cloud Functions
    - [x] Triggering Background Jobs
- [x] Error Codes
- [x] GeoPoints
    - [ ] GeoQueries
    - [ ] Caveats

# Low Priority

- [ ] Schema
    - [ ] Fetch the schema
    - [ ] Adding a schema
    - [ ] Modifying the schema
    - [ ] Removing a schema
- [ ] Hooks
    - [ ] Fetch functions
    - [ ] Fetch triggers
    - [ ] Create function webhook
    - [ ] Edit function webhook
    - [ ] Edit trigger webhook
    - [ ] Delete function webhook
    - [ ] Delete trigger webhook
